# permissions for end users to view webs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: web-viewer-role
rules:
- apiGroups:
  - hw4.ntcu.edu.tw
  resources:
  - webs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hw4.ntcu.edu.tw
  resources:
  - webs/status
  verbs:
  - get