apiVersion: hw4.ntcu.edu.tw/v1alpha1
kind: Web
metadata:
  name: web-sample
spec:
    image: "nginx:1.7.9"
<<<<<<< HEAD
    nodePortNumber: 31234
=======
    nodePortNumber: 30100
>>>>>>> first commit
